### PR TITLE
more things so `make build-packages` works for me

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

### CODE REVIEW

**Comment by SvenDowideit** [comment]
I _think_ we can remove `assets/repositories-build` wdyt?

**Comment by SvenDowideit** [comment]
rsyslog doesn't make it yet:

```
/usr/include
/usr/include/popt.h
/usr/share/locale/de
/usr/share/locale/de/LC_MESSAGES
/usr/share/locale/de/LC_MESSAGES/popt.mo
panic: open /usr/include/acl/libacl.h: no such file or directory

goroutine 9 [running]:
panic(0x77fc20, 0xc4202e3230)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/strato/src/cmd/add.Action.func1(0xc4202ca2c0, 0xc420240b50, 0x1, 0xc420240b60, 0xc420240cf0, 0x6)
	/go/src/github.com/rancher/strato/src/cmd/add/add.go:77 +0x141
created by github.com/rancher/strato/src/cmd/add.Action
	/go/src/github.com/rancher/strato/src/cmd/add/add.go:79 +0x5a8
The command '/bin/sh -c strato add xz-dev acl-dev popt-dev lvm2-dev json-c-dev libestr-dev' returned a non-zero code: 2
DEBU[0001] Failed running /usr/bin/docker [build -f packages/2.rsyslog/Dockerfile -t package packages/2.rsyslog]: exit status 1 
FATA[0001] exit status 1  
```

**Comment by joshwget** [comment]
Yeah, I don't think `assets/repositories-build` is needed anymore. Definitely nice to have this scripted :+1:

**Comment by SvenDowideit** [comment]
@joshwget repositoroes-build removed, and other things updated - it managed to build successfully for me here. 

So I'd say this one is ready to merge

**Pull request merged**
